## node configurations template
node:
  ## the mode of node: authority/storage/watcher
  mode: "authority"
  ## the profile of node: devnet/testnet/mainnet
  profile: "devnet"
  externalChain: 0

## chain configurations
chain:
  ## the name of chain node
  name: "cess-chain"
  ## the p2p port of chain node
  port: 30336
  extraCmdArgs: "-a 333 --anfew afew"

## bucket configurations
bucket:
  chainWsUrl: "ws://127.0.0.1:9944"
  backupChainWsUrls: []
  port: 15001
  space: 300
  incomeAccount: "abc"
  signPhrase: "abc"
  diskPath: "/disks/1"
  bootAddr: "_dnsaddr.bootstrap-kldr.cess.cloud"
  extraCmdArgs: " -bb  ss --sfew 3"

## ceseal configurations
ceseal:
  chainWsUrl: "ws://127.0.0.1:9944"
  endpointOnChain: "http://abc.com:19999"
  publicPort: 19999
  role: Full
  mnemonic: "worth swallow between garage novel repair february panther million report hip token"

nginx:
  confPath: "/opt/cess/authority/proxy/conf"
  logPath: "/opt/cess/authority/proxy/log"