## node configurations template
node:
  ## the mode of node: authority/storage/watcher
  mode: "authority"
  externalIp: "127.0.0.1"
  domainName: ""
  chainWsUrl: "ws://127.0.0.1:9948"
  ## the profile of node: dev/test/prod
  profile: "dev"

## chain configurations
chain:
  ## the name of chain node
  name: "cess-chain"
  ## the p2p port of chain node
  port: 30336
  extraCmdArgs: "-a 333 --anfew afew"

## scheduler configurations
scheduler:
  port: 15000
  stashAccount: "abc"
  controllerPhrase: "abc"
  extraCmdArgs: "-bb afe --fewfew   aa"

## bucket configurations
bucket:
  port: 15001
  space: 300
  incomeAccount: "abc"
  signPhrase: "abc"
  diskPath: "/disks/1"
  extraCmdArgs: " -bb  ss --sfew 3"
