## node configurations template
node:
  ## the mode of node: tee/storage/validator/rpcnode/multiminer
  mode: "multiminer"
  ## the profile of node: devnet/testnet/mainnet
  profile: "testnet"
  # default chain url for miner
  chainWsUrl: ""
  # default backup chain urls for miner
  backupChainWsUrls: []

## chain configurations
chain:
  ## the name of chain node
  name: "cess-chain"
  ## the port of chain node
  port: 30336
  rpcPort: 9044

## miner configurations (single storage miner mode)
miner:
  chainWsUrl: "ws://127.0.0.1:9944/ws/"
  backupChainWsUrls: []
  port: 15001
  space: 300
  incomeAccount: "abc"
  signPhrase: "abc"
  diskPath: "/disks/1"
  bootAddr: "_dnsaddr.bootstrap-kldr.cess.cloud"
  extraCmdArgs: " -bb  ss --sfew 3"
  apiendpoint: ""

## miner configurations  (multi storage miner mode)
miners:
  - name: "miner1"
    # Use this endpoint to receive/send file, can be a domain or ip:port, default value: hostPublicIp:port
    apiendpoint: ""
    port: 15001
    # Maximum space used in each miner, the unit is GiB
    # The declaration space on chain is auto set by the value of `UseSpace after round up to the closest TB` when the miner first run
    # If set UseSpace 2300, that means declare 3 TiB space on the chain
    # If set UseSpace 300, that means declare 1 TiB space on the chain
    UseSpace: 1000
    # Number of cpu's used, 0 means use all
    UseCpu: 2
    # earnings account
    earningsAcc: cXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    # Staking account
    # If you fill in the staking account, the staking will be paid by the staking account you set,
    # otherwise the staking will be paid by the signatureAcc(mnemonic).
    stakingAcc: ""
    # Signature account mnemonic
    # each miner's mnemonic should be different
    mnemonic: "aaaaa bbbbb ccccc ddddd eeeee fffff ggggg hhhhh iiiii jjjjj kkkkk lllll"
    # miner work at this host path
    diskPath: "/mnt/cess_storage1"
    # The rpc endpoint of the chain
    # `official chain: "wss://testnet-rpc.cess.network"`
    chainWsUrl: "ws://127.0.0.1:9944"
    backupChainWsUrls: [ "wss://testnet-rpc.cess.network" ]
    # Default 12 second for transaction with chain
    Timeout: 12
    # Tee list address
    # Attention: Storage miner will not use public tee nodes on chain if set custom tee nodes in config.yaml
    # TeeList:
    #  - 127.0.0.1:8080
    #  - 127.0.0.1:8081

  - name: "miner2"
    apiendpoint: ""
    port: 15002
    UseSpace: 1000
    UseCpu: 2
    earningsAcc: "cXxxx"
    stakingAcc: ""
    mnemonic: "xxx"
    diskPath: "/mnt/cess_storage2"
    chainWsUrl: "ws://127.0.0.1:9944"
    backupChainWsUrls: [ "wss://testnet-rpc.cess.network" ]
    Timeout: 12


# cacher is a gateway which provide an integration interface for all of your storage miners so that user can access all of your storage miners with a unique interface.
cacher:
  # enable is whether to enable the cacher service
  enable: true
  # Workspace is the root directory of all working subdirectories of the node. Please reserve at least 16 GiB of storage space for it.
  WorkSpace: /mnt/cess_cacher
  # default 16GB for storage space
  CacheSize: 17179869184
  # The RPC address of the blockchain where the cache protocol smart contract is deployed, usually the CESS chain
  Rpcs:
    - "ws://127.0.0.1:9944"
    - "ws://testnet-rpc.cess.network"
  # SecretKey is the key of the node working account (Ethereum wallet account), which is used to initiate a call request to the cache protocol contract (working on EVM).
  # By default, it is not filled in, which means that it does not participate in the CD2N network and only has the most basic data interaction with the gateway.
  SecretKey: ""
  # Token is the NFT access certificate for nodes to join the CD2N network and will be released in subsequent versions.
  Token: ""
  # TokenAcc is the holder account(Ethereum wallet account) of the above NFT token.
  TokenAcc: ""
  # TokenAccSign is an Ethereum account signature, which is the token holder's proof of holding the token.
  # Signature methods and tools will be published in the document.
  TokenAccSign: ""
  # CD2N cache protocol contract address, which is responsible for node traffic statistics and reward distribution, and works on EVM.
  ProtoContract: "0xce078A9098dF68189Cbe7A42FC629A4bDCe7dDD4"
  # Local storage nodes configuration file, currently only available for the "Cess Multi-Miner Admin" script.
  # The cacher automatically imports the storage node information started by the script through it.
  MinerConfigPath: /opt/cess/mineradmConf.yaml
  # You can manually configure the following connection options to make the cacher serve the specified retriever node:
  # By default, it points to the CESS official retriever node.
  # If you register your cacher to the cache protocol contract,
  # it will automatically connect to some publicly available retriever nodes to get more opportunities to get rewards.
  CdnNodes:
    - Account: "0xb7B43408864aEa0449D8F813380f8ec424F7a775"
      Endpoint: "https://retriever.cess.network"
  # You can also manually import storage nodes through the following configuration.
  # The cacher will automatically check the availability of the storage node and complete other information from the chain.
  StorageNodes:
    - Account: ""  # CESS account address
      Endpoint: "" # Http address

watchdog:
  # enable miners monitor or not
  enable: false
  # external: run with 0.0.0.0 or 127.0.0.1, env: WATCHDOG_IS_EXTERNAL
  external: true
  # apiUrl: watchdog-web request this apiUrl to fetch data from watchdog: <my_public_ip:13081 or a domain>
  # if empty or null, will set this value to http://<public ip>:13081 automatically
  apiUrl: ""
  # watchdog server listen http port at: 13081, env: WATCHDOG_PORT
  port: 13081
  # the interval of query data from chain for each miner, 1800 <= scrapeInterval <= 3600, env: WATCHDOG_SCRAPE_INTERVAL
  scrapeInterval: 1800
  hosts:
    - ip: 127.0.0.1 # 127.x, 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16 is a private IP
      # make sure docker daemon listen at 2375: https://docs.docker.com/config/daemon/remote-access/
      port: 2375
    # Configure remote access for Docker daemon in public network must use tls to make sure mnemonic safe
    # set ca/crt/key path if the ip no belongs to [ 127.x, 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16 ]
    - ip: 1.1.1.1 # 1.1.1.1 is a public IP
      # make sure docker daemon tls listen at 2376: https://docs.docker.com/engine/security/protect-access/
      port: 2376
      ca_path: /etc/docker/tls/1.1.1.1-ca.pem
      cert_path: /etc/docker/tls/1.1.1.1-cert.pem
      key_path: /etc/docker/tls/1.1.1.1-key.pem
  alert:
    # enable alert or not
    enable: false
    # send webhook to alert someone
    webhook:
      - https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXX
      - https://discordapp.com/api/webhooks/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    # send email to alert someone
    email:
      smtp_endpoint: smtp.example.com
      smtp_port: 80
      smtp_account: myservice@example.com
      smtp_password: my_pwd
      receiver:
        - example1@gmail.com
        - example2@outlook.com
  auth:
    username: "admin" # env: WATCHDOG_USERNAME, default: cess
    password: "passwd" # env: WATCHDOG_PASSWORD, default: Cess123456
    jwt_secret_key: "your-random-secret-key" # env: WATCHDOG_JWT_SECRET
    token_expiry: 1  # 1 hour # env: WATCHDOG_TOKEN_EXPIRY

## ceseal configurations
ceseal:
  chainWsUrl: "ws://127.0.0.1:9944"
  endpointOnChain: "http://example.com:19999"
  publicPort: 19999
  role: full
  mnemonic: "worth swallow between garage novel repair february panther million report hip token"

nginx:
  confPath: "/opt/cess/tee/proxy/conf"
  logPath: "/opt/cess/tee/proxy/log"
