## node configurations template
node:
  ## the mode of node: authority/storage/rpcnode/multibucket
  mode: "multibucket"
  ## the profile of node: devnet/testnet/mainnet
  profile: "testnet"
  # default chain/rpcnode url for bucket
  chainWsUrl: ""
  # default backup chain/rpcnode urls for bucket
  backupChainWsUrls: []

## chain/rpcnode configurations
rpcnode:
  ## the name of chain/rpcnode node
  name: "cess-rpcnode"
  ## the port of chain/rpcnode node
  port: 30336
  rpcPort: 9044

## bucket configurations (single storage miner mode)
bucket:
  chainWsUrl: "ws://127.0.0.1:9944"
  backupChainWsUrls: []
  port: 15001
  space: 300
  incomeAccount: "abc"
  signPhrase: "abc"
  diskPath: "/disks/1"
  bootAddr: "_dnsaddr.bootstrap-kldr.cess.cloud"
  extraCmdArgs: " -bb  ss --sfew 3"

## bucket configurations  (multi storage miner mode)
buckets:
  # P2P communication port
  - name: "bucket_1"
    port: 15001
    # Maximum space used, the unit is GiB
    UseSpace: 1000
    # Number of cpu's used, 0 means use all
    UseCpu: 2
    # earnings account
    earningsAcc: "cXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    # Staking account
    # If you fill in the staking account, the staking will be paid by the staking account,
    # otherwise the staking will be paid by the signature account.
    stakingAcc: "cXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    # Signature account mnemonic
    # each bucket's mnemonic should be different
    mnemonic: "aaaaa bbbbb ccccc ddddd eeeee fffff ggggg hhhhh iiiii jjjjj kkkkk lllll"
    # a directory mount with filesystem
    diskPath: "/mnt/cess_storage1"
    # The rpc endpoint of the chain node
    rpcNodeWsUrl: "ws://127.0.0.1:9944/"
    backupRpcNodeWsUrls: []
    # Priority tee list address
    TeeList:
      - "127.0.0.1:8080"
      - "127.0.0.1:8081"
    # Bootstrap Nodes
    Boot: "_dnsaddr.boot-bucket-testnet.cess.cloud"

  - name: "bucket_2"
    # P2P communication port
    port: 15002
    # Maximum space used, the unit is GiB
    UseSpace: 1000
    # Number of cpu's used
    UseCpu: 2
    # earnings account
    earningsAcc: "cXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    # Staking account
    # If you fill in the staking account, the staking will be paid by the staking account,
    # otherwise the staking will be paid by the signature account.
    stakingAcc: "cXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    # Signature account mnemonic
    # each bucket's mnemonic should be different
    mnemonic: "lllll kkkkk jjjjj iiiii hhhhh ggggg fffff eeeee ddddd ccccc bbbbb aaaaa"
    # a directory mount with filesystem
    diskPath: "/mnt/cess_storage2"
    # The rpc endpoint of the chain node
    rpcNodeWsUrl: "ws://127.0.0.1:9944/"
    backupRpcNodeWsUrls: []
    # Priority tee list address
    TeeList:
      - "127.0.0.1:8080"
      - "127.0.0.1:8081"
    # Bootstrap Nodes
    Boot: "_dnsaddr.boot-bucket-testnet.cess.cloud"


## ceseal configurations
ceseal:
  chainWsUrl: "ws://127.0.0.1:9944"
  endpointOnChain: "http://abc.com:19999"
  publicPort: 19999
  role: Full
  mnemonic: "worth swallow between garage novel repair february panther million report hip token"

nginx:
  confPath: "/opt/cess/authority/proxy/conf"
  logPath: "/opt/cess/authority/proxy/log"
