## node configurations template
node:
  ## the mode of node: authority/storage/watcher/miners
  mode: "miners"
  ## the profile of node: devnet/testnet/mainnet
  profile: "testnet"
  # default chain url for miner
  chainWsUrl: ""
  # default backup chain urls for miner
  backupChainWsUrls: []

## chain configurations
chain:
  ## the name of chain node
  name: "cess-chain"
  ## the port of chain node
  port: 30336
  rpcPort: 9044

## miner configurations (single storage miner mode)
miner:
  chainWsUrl: "ws://127.0.0.1:9944"
  backupChainWsUrls: []
  port: 15001
  space: 300
  incomeAccount: "abc"
  signPhrase: "abc"
  diskPath: "/disks/1"
  bootAddr: "_dnsaddr.bootstrap-kldr.cess.cloud"
  extraCmdArgs: " -bb  ss --sfew 3"

## miner configurations  (multi storage miner mode)
miners:
  # P2P communication port
#  - name: "miner1"
  - port: 15001
    # Maximum space used, the unit is GiB
    UseSpace: 1000
    # Number of cpu's used, 0 means use all
    UseCpu: 2
    # earnings account
    earningsAcc: "cXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    # Staking account
    # If you fill in the staking account, the staking will be paid by the staking account,
    # otherwise the staking will be paid by the signature account.
    stakingAcc: "cXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    # Signature account mnemonic
    # each miner's mnemonic should be different
    mnemonic: "aaaaa bbbbb ccccc ddddd eeeee fffff ggggg hhhhh iiiii jjjjj kkkkk lllll"
    # a directory mount with filesystem
    diskPath: "/mnt/cess_storage1"
    # The rpc endpoint of the chain node
    chainWsUrl: "ws://127.0.0.1:9944/"
    backupChainWsUrls: []
    # Priority tee list address
    TeeList:
      - "127.0.0.1:8080"
      - "127.0.0.1:8081"
    # Bootstrap Nodes
    Boot: "_dnsaddr.boot-miner-testnet.cess.cloud"

#  - name: "miner2"
    # P2P communication port
  - port: 15002
    # Maximum space used, the unit is GiB
    UseSpace: 1000
    # Number of cpu's used
    UseCpu: 2
    # earnings account
    earningsAcc: "cXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    # Staking account
    # If you fill in the staking account, the staking will be paid by the staking account,
    # otherwise the staking will be paid by the signature account.
    stakingAcc: "cXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    # Signature account mnemonic
    # each miner's mnemonic should be different
    mnemonic: "lllll kkkkk jjjjj iiiii hhhhh ggggg fffff eeeee ddddd ccccc bbbbb aaaaa"
    # a directory mount with filesystem
    diskPath: "/mnt/cess_storage2"
    # The rpc endpoint of the chain node
    chainWsUrl: "ws://127.0.0.1:9944/"
    backupChainWsUrls: []
    # Priority tee list address
    TeeList:
      - "127.0.0.1:8080"
      - "127.0.0.1:8081"
    # Bootstrap Nodes
    Boot: "_dnsaddr.boot-miner-testnet.cess.cloud"


## ceseal configurations
ceseal:
  chainWsUrl: "ws://127.0.0.1:9944"
  endpointOnChain: "http://abc.com:19999"
  publicPort: 19999
  role: Full
  mnemonic: "worth swallow between garage novel repair february panther million report hip token"

nginx:
  confPath: "/opt/cess/authority/proxy/conf"
  logPath: "/opt/cess/authority/proxy/log"
