## node configurations template
node:
  ## the mode of node: authority/storage/watcher
  mode: "authority"
  externalIp: "127.0.0.1"
  domainName: ""
  chainWsUrl: "ws://127.0.0.1:9944"
  ## the profile of node: devnet/testnet/mainnet
  profile: "devnet"

## chain configurations
chain:
  ## the name of chain node
  name: "cess-chain"
  ## the p2p port of chain node
  port: 30336
  extraCmdArgs: "-a 333 --anfew afew"

## bucket configurations
bucket:
  port: 15001
  space: 300
  incomeAccount: "abc"
  signPhrase: "abc"
  diskPath: "/disks/1"
  bootAddr: "_dnsaddr.bootstrap-kldr.cess.cloud"
  extraCmdArgs: " -bb  ss --sfew 3"

## kaleido configurations
kaleido:
  kldPort: 4001
  rotPort: 10010
  stashAccount: "cXh9q6D97jZ4XH31SMAGSUNVNsTzg5hThuhoawQFj2szbvsQD"
  controllerPhrase: "worth swallow between garage novel repair february panther million report hip token"

